### ISSUE TITLE
Package no longer works as intended

### ISSUE THREAD

**Issue by kashalls** [ConnorMcF/mixerclient#2]
Upon running the example, the code exits with a code 0.
https://awau.moe/e5b367.png

**Comment by ConnorMcF** [comment]
Hey, thanks for the report. I don't seem to be able to reproduce this though.

Just to confirm you've changed the token via the environment variable and/or constructor and if you could provide your node version that'd be great to help me see what's going on here.

Edit: Also, just to be sure - you are running example/___/index.js rather than the root index.js?
The root one is for exporting the library (e.g.: `let Mixer = require('mixerclient')`) so won't do anything unless you create a new instance of it.

**Comment by kashalls** [comment]
Node Version: v10.11.0
NPM Version: 6.4.1

My Code:
https://awau.moe/c96fe7.png

I am available on Discord if you'd like to check it out.

**Comment by ConnorMcF** [comment]
Looks like the init is missing!

Try adding `mixer.init()` to the bottom.

**Comment by kashalls** [comment]
Well, that was missing from the frontpage example, might want to add that. 

What about this now? https://awau.moe/8c6f00.png

**Comment by ConnorMcF** [comment]
My mistake, will add it shortly.

That should be working as intended?

**Comment by kashalls** [comment]
It replys with pong twice for one ping

**Comment by ConnorMcF** [comment]
Discussing via Discord, will close on resolution.
